export const USERLOGGEDIN = 'USERLOGGEDIN';
export const REGISTRATONCHANGED = 'REGISTRATONCHANGED';
export const LOGINCHAGED = 'LOGINCHAGED';
export const SUBMITREGISTRATIONFORM = 'SUBMITREGISTRATIONFORM';
export const SUBMITLOGINFORM = 'SUBMITLOGINFORM';