export const USERLOGGEDIN = 'USERLOGGEDIN';
export const REDIRECT = 'REDIRECT';

export const LOGINCHAGED = 'LOGINCHAGED';
export const SUBMITLOGINFORM = 'SUBMITLOGINFORM';

export const REGISTRATONCHANGED = 'REGISTRATONCHANGED';
export const SUBMITREGISTRATIONFORM = 'SUBMITREGISTRATIONFORM';

export const GETALLRPODUCTS = 'GETALLRPODUCTS';
